version: '3.4'

services:
  catalogodb:
    image: mongo

  comprasdb:
    image: redis:alpine

  descontodb:
    image: postgres:alpine

  pgadmin:
    image: dpage/pgadmin4

  catalogo.api:
    image: ${DOCKER_REGISTRY-}catalogoapi
    build:
      context: .
      dockerfile: Catalogo.Api/Dockerfile

  compras.api:
    image: ${DOCKER_REGISTRY-}comprasapi
    build:
      context: .
      dockerfile: Compras.Api/Dockerfile
   
  desconto.api:
    image: ${DOCKER_REGISTRY-}descontoapi
    build:
      context: .
      dockerfile: Desconto.Api/Dockerfile

  desconto.grpc:
    image: ${DOCKER_REGISTRY-}descontogrpc
    build:
      context: .
      dockerfile: Desconto.Grpc/Dockerfile

volumes:
  mongo_data:
  postgres_data:
  pgadmin_data:

