version: '3.4'

services:
  catalogodb:
    container_name: catalogodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  comprasdb:
    container_name: comprasdb
    restart: always
    ports:
      - "6379:6379"

  descontodb:
    container_name: descontodb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=DescontoDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/ 

  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@macoratti.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin

  catalogo.api:
    container_name: catalogo.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://catalogodb:27017"
    depends_on:
      - catalogodb
    ports:
      - "8000:80"

  compras.api:
    container_name: compras.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=comprasdb:6379"
    depends_on:
      - comprasdb
    ports:
      - "8001:80"

  desconto.api:
    container_name: desconto.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=descontodb;Port=5432;Database=DescontoDb;User Id=admin;Password=admin1234"
    depends_on:
      - descontodb
    ports:
      - "8002:80"

